<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Dh Key Too Small (Python3 FTP) on Whonix</title>
    <link>http://forums.whonix.org/t/dh-key-too-small-python3-ftp-on-whonix/10622</link>
    <description>I am trying to upload files to a server from within the Whonix operating system. I was able to do it successfully using Filezilla from within Whonix, so I&#39;m not really sure why the Python code isn&#39;t working.

```
from ftplib import FTP, FTP_TLS
import os

ftp = FTP_TLS()
ftp.set_debuglevel(2)
ftp.connect(&#39;ftp.server.com&#39;, 21)
ftp.login(&#39;Username&#39;, &#39;Password&#39;)
item_name = &#39;myfile.mp4&#39;
item_path = os.path.abspath(item_name)

fp = open(item_path, &#39;rb&#39;)
ftp.storbinary(&#39;STOR {}&#39;.format(item_name), fp, 8192)
fp.close()
```

Does anybody know how I should change the Python code to be able to upload the file succesfully from within Whonix? For reference, the Python code works when I run it directly from within Windows. It only fails when I try it from within Whonix, and I don&#39;t know why.

This is the error I get, and I don&#39;t understand it:

```
*get* &#39;220-This is a private system - No anonymous login\n&#39;
*get* &#39;220-IPv6 connections are also welcome on this server.\n&#39;
*get* &#39;220 You will be disconnected after 30 minutes of inactivity.\n&#39;
*resp* &#39;220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------\n220-You are user number 17 of 50 allowed.\n220-Local time is now 01:28. Server port: 21.\n220-This is a private system - No anonymous login\n220-IPv6 connections are also welcome on this server.\n220 You will be disconnected after 30 minutes of inactivity.&#39;
*cmd* &#39;AUTH TLS&#39;
*put* &#39;AUTH TLS\r\n&#39;
*get* &#39;234 AUTH TLS OK.\n&#39;
*resp* &#39;234 AUTH TLS OK.&#39;
Traceback (most recent call last):
  File &quot;test.py&quot;, line 8, in &lt;module&gt;
    ftp.login(&#39;Username&#39;, &#39;Password&#39;)
  File &quot;/usr/lib/python3.7/ftplib.py&quot;, line 749, in login
    self.auth()
  File &quot;/usr/lib/python3.7/ftplib.py&quot;, line 761, in auth
    server_hostname=self.host)
  File &quot;/usr/lib/python3.7/ssl.py&quot;, line 412, in wrap_socket
    session=session
  File &quot;/usr/lib/python3.7/ssl.py&quot;, line 853, in _create
    self.do_handshake()
  File &quot;/usr/lib/python3.7/ssl.py&quot;, line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1056)
```</description>
    <language>en</language>
    <lastBuildDate>Sun, 22 Nov 2020 08:20:08 +0000</lastBuildDate>
    <category>Support</category>
    <atom:link href="http://forums.whonix.org/t/dh-key-too-small-python3-ftp-on-whonix/10622.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Dh Key Too Small (Python3 FTP) on Whonix</title>
        <dc:creator><![CDATA[Patrick]]></dc:creator>
        <description><![CDATA[
            <p>Probably some missing dependency library. Should be resolved as per:</p>
<p><a href="https://www.whonix.org/wiki/Free_Support_Principle">https://www.whonix.org/wiki/Free_Support_Principle</a></p>
          <p><a href="http://forums.whonix.org/t/dh-key-too-small-python3-ftp-on-whonix/10622/4">Read full topic</a></p>
        ]]></description>
        <link>http://forums.whonix.org/t/dh-key-too-small-python3-ftp-on-whonix/10622/4</link>
        <pubDate>Sun, 22 Nov 2020 08:20:08 +0000</pubDate>
        <guid isPermaLink="false">forums.whonix.org-post-10622-4</guid>
        <source url="http://forums.whonix.org/t/dh-key-too-small-python3-ftp-on-whonix/10622.rss">Dh Key Too Small (Python3 FTP) on Whonix</source>
      </item>
      <item>
        <title>Dh Key Too Small (Python3 FTP) on Whonix</title>
        <dc:creator><![CDATA[JohnTravoslki]]></dc:creator>
        <description><![CDATA[
            <p>I need the process automated. The code works in Windows but not in Whonix, so I don’t understand what is fundamentally different.</p>
          <p><a href="http://forums.whonix.org/t/dh-key-too-small-python3-ftp-on-whonix/10622/3">Read full topic</a></p>
        ]]></description>
        <link>http://forums.whonix.org/t/dh-key-too-small-python3-ftp-on-whonix/10622/3</link>
        <pubDate>Sun, 22 Nov 2020 07:54:45 +0000</pubDate>
        <guid isPermaLink="false">forums.whonix.org-post-10622-3</guid>
        <source url="http://forums.whonix.org/t/dh-key-too-small-python3-ftp-on-whonix/10622.rss">Dh Key Too Small (Python3 FTP) on Whonix</source>
      </item>
      <item>
        <title>Dh Key Too Small (Python3 FTP) on Whonix</title>
        <dc:creator><![CDATA[HulaHoop]]></dc:creator>
        <description><![CDATA[
            <aside class="quote no-group" data-username="JohnTravoslki" data-post="1" data-topic="10622">
<div class="title">
<div class="quote-controls"></div>
<img alt="" width="20" height="20" src="//forums.whonix.org/letter_avatar_proxy/v4/letter/j/bbe5ce/40.png" class="avatar"> JohnTravoslki:</div>
<blockquote>
<p>Does anybody know how I should change the Python code to be able to upload the file succesfully from within Whonix? For reference, the Python code works when I run it directly from within Windows. It only fails when I try it from within Whonix, and I don’t know why.</p>
</blockquote>
</aside>
<p>This isn’t a coding help forum. If Filezilla works why switch?</p>
          <p><a href="http://forums.whonix.org/t/dh-key-too-small-python3-ftp-on-whonix/10622/2">Read full topic</a></p>
        ]]></description>
        <link>http://forums.whonix.org/t/dh-key-too-small-python3-ftp-on-whonix/10622/2</link>
        <pubDate>Sat, 21 Nov 2020 15:09:19 +0000</pubDate>
        <guid isPermaLink="false">forums.whonix.org-post-10622-2</guid>
        <source url="http://forums.whonix.org/t/dh-key-too-small-python3-ftp-on-whonix/10622.rss">Dh Key Too Small (Python3 FTP) on Whonix</source>
      </item>
      <item>
        <title>Dh Key Too Small (Python3 FTP) on Whonix</title>
        <dc:creator><![CDATA[JohnTravoslki]]></dc:creator>
        <description><![CDATA[
            <p>I am trying to upload files to a server from within the Whonix operating system. I was able to do it successfully using Filezilla from within Whonix, so I’m not really sure why the Python code isn’t working.</p>
<pre><code class="lang-auto">from ftplib import FTP, FTP_TLS
import os

ftp = FTP_TLS()
ftp.set_debuglevel(2)
ftp.connect('ftp.server.com', 21)
ftp.login('Username', 'Password')
item_name = 'myfile.mp4'
item_path = os.path.abspath(item_name)

fp = open(item_path, 'rb')
ftp.storbinary('STOR {}'.format(item_name), fp, 8192)
fp.close()
</code></pre>
<p>Does anybody know how I should change the Python code to be able to upload the file succesfully from within Whonix? For reference, the Python code works when I run it directly from within Windows. It only fails when I try it from within Whonix, and I don’t know why.</p>
<p>This is the error I get, and I don’t understand it:</p>
<pre><code class="lang-auto">*get* '220-This is a private system - No anonymous login\n'
*get* '220-IPv6 connections are also welcome on this server.\n'
*get* '220 You will be disconnected after 30 minutes of inactivity.\n'
*resp* '220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------\n220-You are user number 17 of 50 allowed.\n220-Local time is now 01:28. Server port: 21.\n220-This is a private system - No anonymous login\n220-IPv6 connections are also welcome on this server.\n220 You will be disconnected after 30 minutes of inactivity.'
*cmd* 'AUTH TLS'
*put* 'AUTH TLS\r\n'
*get* '234 AUTH TLS OK.\n'
*resp* '234 AUTH TLS OK.'
Traceback (most recent call last):
  File "test.py", line 8, in &lt;module&gt;
    ftp.login('Username', 'Password')
  File "/usr/lib/python3.7/ftplib.py", line 749, in login
    self.auth()
  File "/usr/lib/python3.7/ftplib.py", line 761, in auth
    server_hostname=self.host)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1056)
</code></pre>
          <p><a href="http://forums.whonix.org/t/dh-key-too-small-python3-ftp-on-whonix/10622/1">Read full topic</a></p>
        ]]></description>
        <link>http://forums.whonix.org/t/dh-key-too-small-python3-ftp-on-whonix/10622/1</link>
        <pubDate>Fri, 20 Nov 2020 21:44:07 +0000</pubDate>
        <guid isPermaLink="false">forums.whonix.org-post-10622-1</guid>
        <source url="http://forums.whonix.org/t/dh-key-too-small-python3-ftp-on-whonix/10622.rss">Dh Key Too Small (Python3 FTP) on Whonix</source>
      </item>
  </channel>
</rss>
