<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Problem installing Riseup-VPN via Snap</title>
    <link>http://forums.whonix.org/t/problem-installing-riseup-vpn-via-snap/13681</link>
    <description>Hello, I have encountered a problem when installing riseup-vpn via snap, in appvm in my qubes os.

I created a minimal debian-11 template and installed security enhancements from the kicksecure team into it, then I installed the packages qubes-core-agent-networking and snapd along with qubes-snapd-helper. After that I started installing riseup vpn with snap install --classic riseup-vpn and at the end I keep getting an error: 

user@sys-vpn:~$ sudo snap install --classic riseup-vpn
2022-05-16T22:05:13-04:00 INFO Waiting for automatic snapd restart...
error: cannot perform the following tasks:
- Run install hook of &quot;riseup-vpn&quot; snap if present (run hook &quot;install&quot;: 
-----
Traceback (most recent call last):
  File &quot;/snap/riseup-vpn/179/meta/hooks/install&quot;, line 26, in &lt;module&gt;
    subprocess.call([&#39;update-desktop-database&#39;])
  File &quot;/usr/lib/python3.9/subprocess.py&quot;, line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File &quot;/usr/lib/python3.9/subprocess.py&quot;, line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File &quot;/usr/lib/python3.9/subprocess.py&quot;, line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: &#39;update-desktop-database&#39;
-----)

Maybe someone has encountered this? I&#39;ve already tried installing qubes-core-agent-passwordless-root and different versions of python, but I still get the same error. 

Thank you.

Translated with www.DeepL.com/Translator (free version)</description>
    <language>en</language>
    <lastBuildDate>Wed, 18 May 2022 13:42:15 +0000</lastBuildDate>
    <category>Support</category>
    <atom:link href="http://forums.whonix.org/t/problem-installing-riseup-vpn-via-snap/13681.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Problem installing Riseup-VPN via Snap</title>
        <dc:creator><![CDATA[Patrick]]></dc:creator>
        <description><![CDATA[
            <p>Try with plain Debian if the same issue is happening. If so → <a href="https://www.whonix.org/wiki/Unspecific" class="inline-onebox">Information Booster might be Available!</a></p>
          <p><a href="http://forums.whonix.org/t/problem-installing-riseup-vpn-via-snap/13681/2">Read full topic</a></p>
        ]]></description>
        <link>http://forums.whonix.org/t/problem-installing-riseup-vpn-via-snap/13681/2</link>
        <pubDate>Wed, 18 May 2022 13:42:15 +0000</pubDate>
        <guid isPermaLink="false">forums.whonix.org-post-13681-2</guid>
        <source url="http://forums.whonix.org/t/problem-installing-riseup-vpn-via-snap/13681.rss">Problem installing Riseup-VPN via Snap</source>
      </item>
      <item>
        <title>Problem installing Riseup-VPN via Snap</title>
        <dc:creator><![CDATA[grassdes]]></dc:creator>
        <description><![CDATA[
            <p>Hello, I have encountered a problem when installing riseup-vpn via snap, in appvm in my qubes os.</p>
<p>I created a minimal debian-11 template and installed security enhancements from the kicksecure team into it, then I installed the packages qubes-core-agent-networking and snapd along with qubes-snapd-helper. After that I started installing riseup vpn with snap install --classic riseup-vpn and at the end I keep getting an error:</p>
<p>user@sys-vpn:~$ sudo snap install --classic riseup-vpn<br>
2022-05-16T22:05:13-04:00 INFO Waiting for automatic snapd restart…<br>
error: cannot perform the following tasks:</p>
<ul>
<li>Run install hook of “riseup-vpn” snap if present (run hook “install”:</li>
</ul>
<hr>
<p>Traceback (most recent call last):<br>
File “/snap/riseup-vpn/179/meta/hooks/install”, line 26, in <br>
subprocess.call([‘update-desktop-database’])<br>
File “/usr/lib/python3.9/subprocess.py”, line 349, in call<br>
with Popen(*popenargs, **kwargs) as p:<br>
File “/usr/lib/python3.9/subprocess.py”, line 951, in <strong>init</strong><br>
self._execute_child(args, executable, preexec_fn, close_fds,<br>
File “/usr/lib/python3.9/subprocess.py”, line 1823, in _execute_child<br>
raise child_exception_type(errno_num, err_msg, err_filename)<br>
FileNotFoundError: [Errno 2] No such file or directory: ‘update-desktop-database’<br>
-----)</p>
<p>Maybe someone has encountered this? I’ve already tried installing qubes-core-agent-passwordless-root and different versions of python, but I still get the same error.</p>
<p>Thank you.</p>
<p>Translated with <a href="http://www.DeepL.com/Translator" class="inline-onebox" rel="noopener nofollow ugc">DeepL Translate: The world's most accurate translator</a> (free version)</p>
          <p><a href="http://forums.whonix.org/t/problem-installing-riseup-vpn-via-snap/13681/1">Read full topic</a></p>
        ]]></description>
        <link>http://forums.whonix.org/t/problem-installing-riseup-vpn-via-snap/13681/1</link>
        <pubDate>Wed, 18 May 2022 13:40:27 +0000</pubDate>
        <guid isPermaLink="false">forums.whonix.org-post-13681-1</guid>
        <source url="http://forums.whonix.org/t/problem-installing-riseup-vpn-via-snap/13681.rss">Problem installing Riseup-VPN via Snap</source>
      </item>
  </channel>
</rss>
